
server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
spring:
  profiles:
    active: local
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.learn.webapp: trace
